### ISSUE TITLE
Context 丢失无法连续对话

### ISSUE THREAD

**Issue by oklai** [xing61/xiaoyi-robot#10]
![image](https://github.com/xing61/xiaoyi-robot/assets/795493/83602cc3-6557-4405-bfb1-b4f1dc1f5bf3)
如图，连续发起调用，但系统无法读取到上下文。

**Comment by oklai** [comment]
```javascript
async function main() {
  const completion = await openai.chat.completions.create({
    messages: [
      { role: "user", content: "请写一首四言古诗" },
    ],
    model: "gpt-4-1106-preview",
  });

  console.log(completion.choices[0]);
}

main();
```

**Comment by xing61** [comment]
这是api，连续对话的问题需要自己来处理逻辑的。openai也好，文心一言也好，这些大模型可不管你的上下文哦

**Comment by xing61** [comment]
可以看下这个：https://zhuanlan.zhihu.com/p/657175332
![1700820340450](https://github.com/xing61/xiaoyi-robot/assets/38256442/51c46d73-1195-4899-8122-8166c9b00e50)
