### ISSUE TITLE
whisper

### ISSUE THREAD

**Issue by Jade233333** [xing61/xiaoyi-robot#4]
是不是不支持whisper 模型

**Comment by Jade233333** [comment]
我在使用gtp的时候没有问题, 但是在用whisper的时候报错
/Users/jade/PycharmProjects/pythonProject/venv/bin/python /Users/jade/PycharmProjects/pythonProject/main.py 
Traceback (most recent call last):
  File "/Users/jade/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/openai/api_requestor.py", line 755, in _interpret_response_line
    data = json.loads(rbody)
           ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jade/PycharmProjects/pythonProject/main.py", line 156, in <module>
    transcription = transcribe_audio(audio_file_path)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jade/PycharmProjects/pythonProject/main.py", line 17, in transcribe_audio
    transcription = openai.Audio.transcribe("whisper-1", audio_file)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jade/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/openai/api_resources/audio.py", line 67, in transcribe
    response, _, api_key = requestor.request("post", url, files=files, params=data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jade/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jade/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/Users/jade/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/openai/api_requestor.py", line 757, in _interpret_response_line
    raise error.APIError(
openai.error.APIError: HTTP code 404 from API (<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>系统发生错误</title>
    <meta name="robots" content="noindex,nofollow" />
    <style>
        /* Base */
        body {
            color: #333;
            font: 16px Verdana, "Helvetica Neue", helvetica, Arial, 'Microsoft YaHei', sans-serif;
            margin: 0;
            padding: 0 20px 20px;
        }
        h1{
            margin: 10px 0 0;
            font-size: 28px;
            font-weight: 500;
            line-height: 32px;
        }
        h2{
            color: #4288ce;
            font-weight: 400;
            padding: 6px 0;
            margin: 6px 0 0;
            font-size: 18px;
            border-bottom: 1px solid #eee;
        }
        h3{
            margin: 12px;
            font-size: 16px;
            font-weight: bold;
        }
        abbr{
            cursor: help;
            text-decoration: underline;
            text-decoration-style: dotted;
        }
        a{
            color: #868686;
            cursor: pointer;
        }
        a:hover{
            text-decoration: underline;
        }
        .line-error{
            background: #f8cbcb;
        }

        .echo table {
            width: 100%;
        }

        .echo pre {
            padding: 16px;
            overflow: auto;
            font-size: 85%;
            line-height: 1.45;
            background-color: #f7f7f7;
            border: 0;
            border-radius: 3px;
            font-family: Consolas, "Liberation Mono", Menlo, Courier, monospace;
        }

        .echo pre > pre {
            padding: 0;
            margin: 0;
        }
    
        /* Exception Info */
        .exception {
            margin-top: 20px;
        }
        .exception .message{
            padding: 12px;
            border: 1px solid #ddd;
            border-bottom: 0 none;
            line-height: 18px;
            font-size:16px;
            border-top-left-radius: 4px;
            border-top-right-radius: 4px;
            font-family: Consolas,"Liberation Mono",Courier,Verdana,"微软雅黑";
        }

        .exception .code{
            float: left;
            text-align: center;
            color: #fff;
            margin-right: 12px;
            padding: 16px;
            border-radius: 4px;
            background: #999;
        }
        .exception .source-code{
            padding: 6px;
            border: 1px solid #ddd;

            background: #f9f9f9;
            overflow-x: auto;

        }
        .exception .source-code pre{
            margin: 0;
        }
        .exception .source-code pre ol{
            margin: 0;
            color: #4288ce;
            display: inline-block;
            min-width: 100%;
            box-sizing: border-box;
        font-size:14px;
            font-family: "Century Gothic",Consolas,"Liberation Mono",Courier,Verdana;
            padding-left: 48px;
        }
        .exception .source-code pre li{
            border-left: 1px solid #ddd;
            height: 18px;
            line-height: 18px;
        }
        .exception .source-code pre code{
            color: #333;
            height: 100%;
            display: inline-block;
            border-left: 1px solid #fff;
        font-size:14px;
            font-family: Consolas,"Liberation Mono",Courier,Verdana,"微软雅黑";
        }
        .exception .trace{
            padding: 6px;
            border: 1px solid #ddd;
            border-top: 0 none;
            line-height: 16px;
        font-size:14px;
            font-family: Consolas,"Liberation Mono",Courier,Verdana,"微软雅黑";
        }
        .exception .trace ol{
            margin: 12px;
        }
        .exception .trace ol li{
            padding: 2px 4px;
        }
        .exception div:last-child{
            border-bottom-left-radius: 4px;
            border-bottom-right-radius: 4px;
        }

        /* Exception Variables */
        .exception-var table{
            width: 100%;
            margin: 12px 0;
            box-sizing: border-box;
            table-layout:fixed;
            word-wrap:break-word;            
        }
        .exception-var table caption{
            text-align: left;
            font-size: 16px;
            font-weight: bold;
            padding: 6px 0;
        }
        .exception-var table caption small{
            font-weight: 300;
            display: inline-block;
            margin-left: 10px;
            color: #ccc;
        }
        .exception-var table tbody{
            font-size: 13px;
            font-family: Consolas,"Liberation Mono",Courier,"微软雅黑";
        }
        .exception-var table td{
            padding: 0 6px;
            vertical-align: top;
            word-break: break-all;
        }
        .exception-var table td:first-child{
            width: 28%;
            font-weight: bold;
            white-space: nowrap;
        }
        .exception-var table td pre{
            margin: 0;
        }

        /* Copyright Info */
        .copyright{
            margin-top: 24px;
            padding: 12px 0;
            border-top: 1px solid #eee;
        }

        /* SPAN elements with the classes below are added by prettyprint. */
        pre.prettyprint .pln { color: #000 }  /* plain text */
        pre.prettyprint .str { color: #080 }  /* string content */
        pre.prettyprint .kwd { color: #008 }  /* a keyword */
        pre.prettyprint .com { color: #800 }  /* a comment */
        pre.prettyprint .typ { color: #606 }  /* a type name */
        pre.prettyprint .lit { color: #066 }  /* a literal value */
        /* punctuation, lisp open bracket, lisp close bracket */
        pre.prettyprint .pun, pre.prettyprint .opn, pre.prettyprint .clo { color: #660 }
        pre.prettyprint .tag { color: #008 }  /* a markup tag name */
        pre.prettyprint .atn { color: #606 }  /* a markup attribute name */
        pre.prettyprint .atv { color: #080 }  /* a markup attribute value */
        pre.prettyprint .dec, pre.prettyprint .var { color: #606 }  /* a declaration; a variable name */
        pre.prettyprint .fun { color: red }  /* a function name */
    </style>
</head>
<body>
    <div class="echo">
            </div>
        <div class="exception">
    <div class="message">
        
            <div class="info">
                <div>
                    <h2>[0]&nbsp;<abbr title="think\exception\HttpException">HttpException</abbr> in <a class="toggle" title="/home/wwwroot/chatgpt/thinkphp/library/think/route/dispatch/Module.php line 62">Module.php line 62</a></h2>
                </div>
                <div><h1>模块不存在:api</h1></div>
            </div>
        
    </div>
	        <div class="source-code">
            <pre class="prettyprint lang-php"><ol start="53"><li class="line-53"><code>                $available = true;
</code></li><li class="line-54"><code>            }
</code></li><li class="line-55"><code>
</code></li><li class="line-56"><code>            // 模块初始化
</code></li><li class="line-57"><code>            if ($module &amp;&amp; $available) {
</code></li><li class="line-58"><code>                // 初始化模块
</code></li><li class="line-59"><code>                $this-&gt;request-&gt;setModule($module);
</code></li><li class="line-60"><code>                $this-&gt;app-&gt;init($module);
</code></li><li class="line-61"><code>            } else {
</code></li><li class="line-62"><code>                throw new HttpException(404, 'module not exists:' . $module);
</code></li><li class="line-63"><code>            }
</code></li><li class="line-64"><code>        }
</code></li><li class="line-65"><code>
</code></li><li class="line-66"><code>        // 是否自动转换控制器和操作名
</code></li><li class="line-67"><code>        $convert = is_bool($this-&gt;convert) ? $this-&gt;convert : $this-&gt;rule-&gt;getConfig('url_convert');
</code></li><li class="line-68"><code>        // 获取控制器名
</code></li><li class="line-69"><code>        $controller = strip_tags($result[1] ?: $this-&gt;rule-&gt;getConfig('default_controller'));
</code></li><li class="line-70"><code>
</code></li><li class="line-71"><code>        $this-&gt;controller = $convert ? strtolower($controller) : $controller;
</code></li></ol></pre>
        </div>
	        <div class="trace">
            <h2>Call Stack</h2>
            <ol>
                <li>in <a class="toggle" title="/home/wwwroot/chatgpt/thinkphp/library/think/route/dispatch/Module.php line 62">Module.php line 62</a></li>
                                <li>
                at <abbr title="think\route\dispatch\Module">Module</abbr>->init() in <a class="toggle" title="/home/wwwroot/chatgpt/thinkphp/library/think/route/dispatch/Url.php line 25">Url.php line 25</a>                </li>
                                <li>
                at <abbr title="think\route\dispatch\Url">Url</abbr>->init() in <a class="toggle" title="/home/wwwroot/chatgpt/thinkphp/library/think/App.php line 402">App.php line 402</a>                </li>
                                <li>
                at <abbr title="think\App">App</abbr>->run() in <a class="toggle" title="/home/wwwroot/chatgpt/public/index.php line 25">index.php line 25</a>                </li>
                            </ol>
        </div>
    </div>
        
    
        <div class="exception-var">
        <h2>Environment Variables</h2>
                <table>
                        <caption>GET Data<small>empty</small></caption>
                    </table>
                <table>
                        <caption>POST Data</caption>
            <tbody>
                                <tr>
                    <td>model</td>
                    <td>
                        whisper-1                    </td>
                </tr>
                            </tbody>
                    </table>
                <table>
                        <caption>Files</caption>
            <tbody>
                                <tr>
                    <td>file</td>
                    <td>
                        {
    &quot;name&quot;: &quot;innerfish_chunk_33.wav&quot;,
    &quot;type&quot;: &quot;application\/octet-stream&quot;,
    &quot;tmp_name&quot;: &quot;\/tmp\/phpCAKNev&quot;,
    &quot;error&quot;: 0,
    &quot;size&quot;: 20697516
}                    </td>
                </tr>
                            </tbody>
                    </table>
                <table>
                        <caption>Cookies<small>empty</small></caption>
                    </table>
                <table>
                        <caption>Session<small>empty</small></caption>
                    </table>
                <table>
                        <caption>Server/Request Data</caption>
            <tbody>
                                <tr>
                    <td>TEMP</td>
                    <td>
                        /tmp                    </td>
                </tr>
                                <tr>
                    <td>TMPDIR</td>
                    <td>
                        /tmp                    </td>
                </tr>
                                <tr>
                    <td>TMP</td>
                    <td>
                        /tmp                    </td>
                </tr>
                                <tr>
                    <td>PATH</td>
                    <td>
                        /usr/local/bin:/usr/bin:/bin                    </td>
                </tr>
                                <tr>
                    <td>USER</td>
                    <td>
                        www                    </td>
                </tr>
                                <tr>
                    <td>HOME</td>
                    <td>
                        /home/www                    </td>
                </tr>
                                <tr>
                    <td>PATH_TRANSLATED</td>
                    <td>
                        /home/wwwroot/chatgpt/public/api/v1/audio/transcriptions                    </td>
                </tr>
                                <tr>
                    <td>ORIG_SCRIPT_FILENAME</td>
                    <td>
                        /home/wwwroot/chatgpt/public/index.php/api/v1/audio/transcriptions                    </td>
                </tr>
                                <tr>
                    <td>HTTP_X_OPENAI_CLIENT_USER_AGENT</td>
                    <td>
                        {&quot;bindings_version&quot;: &quot;0.27.9&quot;, &quot;httplib&quot;: &quot;requests&quot;, &quot;lang&quot;: &quot;python&quot;, &quot;lang_version&quot;: &quot;3.11.3&quot;, &quot;platform&quot;: &quot;macOS-13.4.1-arm64-arm-64bit&quot;, &quot;publisher&quot;: &quot;openai&quot;, &quot;uname&quot;: &quot;Darwin 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:21:34 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8112 arm64 arm&quot;}                    </td>
                </tr>
                                <tr>
                    <td>HTTP_CONTENT_TYPE</td>
                    <td>
                        multipart/form-data; boundary=56efeddd0f6519c445db0424ab03ac12                    </td>
                </tr>
                                <tr>
                    <td>HTTP_AUTHORIZATION</td>
                    <td>
                        Bearer ce20e3ad7074b6ec17c4be1aa7891c8d                    </td>
                </tr>
                                <tr>
                    <td>HTTP_ACCEPT_ENCODING</td>
                    <td>
                        gzip, deflate                    </td>
                </tr>
                                <tr>
                    <td>HTTP_ACCEPT</td>
                    <td>
                        */*                    </td>
                </tr>
                                <tr>
                    <td>HTTP_CONTENT_LENGTH</td>
                    <td>
                        20697841                    </td>
                </tr>
                                <tr>
                    <td>HTTP_USER_AGENT</td>
                    <td>
                        OpenAI/v1 PythonBindings/0.27.9                    </td>
                </tr>
                                <tr>
                    <td>HTTP_HOST</td>
                    <td>
                        flag.smarttrot.com                    </td>
                </tr>
                                <tr>
                    <td>REDIRECT_STATUS</td>
                    <td>
                        200                    </td>
                </tr>
                                <tr>
                    <td>SERVER_NAME</td>
                    <td>
                        flag.smarttrot.com                    </td>
                </tr>
                                <tr>
                    <td>SERVER_PORT</td>
                    <td>
                        80                    </td>
                </tr>
                                <tr>
                    <td>SERVER_ADDR</td>
                    <td>
                        47.92.242.146                    </td>
                </tr>
                                <tr>
                    <td>REMOTE_PORT</td>
                    <td>
                        24232                    </td>
                </tr>
                                <tr>
                    <td>REMOTE_ADDR</td>
                    <td>
                        180.98.2.116                    </td>
                </tr>
                                <tr>
                    <td>SERVER_SOFTWARE</td>
                    <td>
                        nginx/1.22.0                    </td>
                </tr>
                                <tr>
                    <td>GATEWAY_INTERFACE</td>
                    <td>
                        CGI/1.1                    </td>
                </tr>
                                <tr>
                    <td>REQUEST_SCHEME</td>
                    <td>
                        http                    </td>
                </tr>
                                <tr>
                    <td>SERVER_PROTOCOL</td>
                    <td>
                        HTTP/1.1                    </td>
                </tr>
                                <tr>
                    <td>DOCUMENT_ROOT</td>
                    <td>
                        /home/wwwroot/chatgpt/public                    </td>
                </tr>
                                <tr>
                    <td>DOCUMENT_URI</td>
                    <td>
                        /index.php/api/v1/audio/transcriptions                    </td>
                </tr>
                                <tr>
                    <td>REQUEST_URI</td>
                    <td>
                        /index.php/api/v1/audio/transcriptions                    </td>
                </tr>
                                <tr>
                    <td>CONTENT_LENGTH</td>
                    <td>
                        20697841                    </td>
                </tr>
                                <tr>
                    <td>CONTENT_TYPE</td>
                    <td>
                        multipart/form-data; boundary=56efeddd0f6519c445db0424ab03ac12                    </td>
                </tr>
                                <tr>
                    <td>REQUEST_METHOD</td>
                    <td>
                        POST                    </td>
                </tr>
                                <tr>
                    <td>QUERY_STRING</td>
                    <td>
                                            </td>
                </tr>
                                <tr>
                    <td>SCRIPT_NAME</td>
                    <td>
                        /index.php/api/v1/audio/transcriptions                    </td>
                </tr>
                                <tr>
                    <td>SCRIPT_FILENAME</td>
                    <td>
                        /home/wwwroot/chatgpt/public/index.php                    </td>
                </tr>
                                <tr>
                    <td>PATH_INFO</td>
                    <td>
                        /api/v1/audio/transcriptions                    </td>
                </tr>
                                <tr>
                    <td>FCGI_ROLE</td>
                    <td>
                        RESPONDER                    </td>
                </tr>
                                <tr>
                    <td>PHP_SELF</td>
                    <td>
                        /index.php/api/v1/audio/transcriptions/api/v1/audio/transcriptions                    </td>
                </tr>
                                <tr>
                    <td>REQUEST_TIME_FLOAT</td>
                    <td>
                        1693051883.075                    </td>
                </tr>
                                <tr>
                    <td>REQUEST_TIME</td>
                    <td>
                        1693051883                    </td>
                </tr>
                            </tbody>
                    </table>
                <table>
                        <caption>Environment Variables<small>empty</small></caption>
                    </table>
                <table>
                        <caption>ThinkPHP Constants</caption>
            <tbody>
                                <tr>
                    <td>FILTER_VALIDATE_BOOL</td>
                    <td>
                        258                    </td>
                </tr>
                            </tbody>
                    </table>
            </div>
    
    <div class="copyright">
        <a title="官方网站" href="http://www.thinkphp.cn">ThinkPHP</a> 
        <span>V5.1.41 LTS</span> 
        <span>{ 十年磨一剑-为API开发设计的高性能框架 }</span>
    </div>
        <script>
        var LINE = 62;

        function $(selector, node){
            var elements;

            node = node || document;
            if(document.querySelectorAll){
                elements = node.querySelectorAll(selector);
            } else {
                switch(selector.substr(0, 1)){
                    case '#':
                        elements = [node.getElementById(selector.substr(1))];
                        break;
                    case '.':
                        if(document.getElementsByClassName){
                            elements = node.getElementsByClassName(selector.substr(1));
                        } else {
                            elements = get_elements_by_class(selector.substr(1), node);
                        }
                        break;
                    default:
                        elements = node.getElementsByTagName();
                }
            }
            return elements;

            function get_elements_by_class(search_class, node, tag) {
                var elements = [], eles, 
                    pattern  = new RegExp('(^|\\s)' + search_class + '(\\s|$)');

                node = node || document;
                tag  = tag  || '*';

                eles = node.getElementsByTagName(tag);
                for(var i = 0; i < eles.length; i++) {
                    if(pattern.test(eles[i].className)) {
                        elements.push(eles[i])
                    }
                }

                return elements;
            }
        }

        $.getScript = function(src, func){
            var script = document.createElement('script');
            
            script.async  = 'async';
            script.src    = src;
            script.onload = func || function(){};
            
            $('head')[0].appendChild(script);
        }

        ;(function(){
            var files = $('.toggle');
            var ol    = $('ol', $('.prettyprint')[0]);
            var li    = $('li', ol[0]);   

            // 短路径和长路径变换
            for(var i = 0; i < files.length; i++){
                files[i].ondblclick = function(){
                    var title = this.title;

                    this.title = this.innerHTML;
                    this.innerHTML = title;
                }
            }

            // 设置出错行
            var err_line = $('.line-' + LINE, ol[0])[0];
            err_line.className = err_line.className + ' line-error';

            $.getScript('//cdn.bootcss.com/prettify/r298/prettify.min.js', function(){
                prettyPrint();

                // 解决Firefox浏览器一个很诡异的问题
                // 当代码高亮后，ol的行号莫名其妙的错位
                // 但是只要刷新li里面的html重新渲染就没有问题了
                if(window.navigator.userAgent.indexOf('Firefox') >= 0){
                    ol[0].innerHTML = ol[0].innerHTML;
                }
            });

        })();
    </script>
    </body>
</html>
)

Process finished with exit code 1

**Comment by xing61** [comment]
支持的。我看一下什么问题

**Comment by Jade233333** [comment]
好的, 理论上支持的就行, 我今天有时间再测试一下

**Comment by Jade233333** [comment]
今天调试了一下, 同样的代码, 我是用自己的apikey和openai的baseurl调用whisper就没有问题, 但是换成项目的base-url就会报错

**Comment by xing61** [comment]
> 今天调试了一下, 同样的代码, 我是用自己的apikey和openai的baseurl调用whisper就没有问题, 但是换成项目的base-url就会报错

解决了。代码在这里，可以试下：
![微信截图_20230829022631](https://github.com/xing61/xiaoyi-robot/assets/38256442/7af9be11-fc09-4d81-83ca-b0670cd5eb2e)

**Comment by Jade233333** [comment]
好的谢谢
