### ISSUE TITLE
OpenAIEmbeddings() 接口是否做了平替

### ISSUE THREAD

**Issue by WGKLoveStudy** [xing61/xiaoyi-robot#8]
你好，刚接触python，最近跟着一个教程学习langchain，在学到把 文件嵌入到向量数据库时，接口报错了，OPENAI_API_KEY和OPENAI_API_BASE已替换，具体代码截图和报错如截图：
![image](https://github.com/xing61/xiaoyi-robot/assets/20789962/17842d01-5b77-4bfd-9c4b-f587a611ac71)
![image](https://github.com/xing61/xiaoyi-robot/assets/20789962/8da0f8cf-cb8d-4d20-8af2-3d3c9253c5ef)
![image](https://github.com/xing61/xiaoyi-robot/assets/20789962/9c61f39a-46a0-4482-ad60-ec1974668486)
这种情况该如何处理，是否是我使用方式不对

**Comment by xing61** [comment]
所有openai的接口，基本都是平替的。embedding是可以的
包括很多向量方式实现的文档问答都是支持的。
你这个应该是哪里调用的不大对，把参数和返回打印出来看看？？
![微信截图_20231007165550](https://github.com/xing61/xiaoyi-robot/assets/38256442/94e21f8f-2d66-4d37-8b71-332518896e6b)

**Comment by WGKLoveStudy** [comment]
<img width="683" alt="b5fcefc8d7d7460ffc4d2618cbbe4a8" src="https://github.com/xing61/xiaoyi-robot/assets/20789962/7982c67a-4261-47f1-bc5d-dbbe5c07545b">
打印了参数




第一个参数embedding ：
client=<class 'openai.api_resources.embedding.Embedding'> model='text-embedding-ada-002' deployment='text-embedding-ada-002' openai_api_version='' openai_api_base='http://flag.smarttrot.com/index.php/api/v1' openai_api_type='' openai_proxy='' embedding_ctx_length=8191 openai_api_key='*************' openai_organization='' allowed_special=set() disallowed_special='all' chunk_size=1000 max_retries=6 request_timeout=None headers=None tiktoken_model_name=None show_progress_bar=False model_kwargs={} skip_empty=False

第二个参数chunked_documents（参数过长，删除掉了中间的一部分）：
[Document(page_content='易速鲜花集团 \n \n \n \n \n \n \n \n \n \n \n易速鲜花 服务中心  \n易速鲜花 股份有限公司  易\n速\n鲜\n花\n员\n工\n手\n册', metadata={'source': '.\\OneFlower\\易速鲜花员工手册.pdf', 'page': 0}), Document(page_content='易速鲜花集团 \n 1 董事长致辞  \n亲爱的同事：  \n您好！欢迎您加入 易速鲜花 旅游文化股份有限公司 ! \n我代表易速鲜花 对您的到来表示热烈的欢迎！并为公司拥有您\n这样优秀的员工而感到自豪和骄傲。 易速鲜花 将会因您的努力工作\n而稳步健康发展，将会因您的贡献而更加精彩。在此，我为您即将\n为易速鲜花 而付出的辛勤汗水表示诚挚的感谢！', metadata={'source': '.\\OneFlower\\易速鲜花员工手册.pdf', 'page': 1}), Document(page_content='易速鲜花 这个大家庭需要您、我、他每一位员工积极发扬“ 团\n结向上，完美无缺 ”的企业精神，以高度的主人翁责任感、使命感，\n与易速鲜花 同呼吸、共命 运，在各自的岗位上，勤奋敬业，尽职尽\n责，奋力拼搏。作为大家庭的一员，同仁之间应默契配合，相互接\n纳，取长补短，共同奋进，同舟共济。这样，我们就可以成为一个\n坚强的战斗堡垒， 在创 易速鲜花 发展的道路上披荆斩棘， 乘风破浪，', metadata={'source': '.\\OneFlower\\易速鲜花员工手册.pdf', 'page': 1}), Document(page_content='无往不胜，所向披靡。最终以一流的服务、一流的管理、一流的信\n誉让我们的 易速鲜花 成为全国的一颗明珠。  \n希望各位以本手册为指南，共创 易速鲜花 美好明天 ! \n最后，诚挚地祝愿大家在公司工作愉快，前程似锦 ! \n \n \n                    签名：', metadata={'source': '.\\OneFlower\\易速鲜花员工手册.pdf', 'page': 1}), Document(page_content='易速鲜花集团 \n 2 易速鲜花 晨会宣言  \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n  \n今天 \n我开始新的生活  \n我要用全身心的爱迎接今天  \n我会用我全部的热情  \n关爱我的同事  \n热爱我们的公司  \n服务于我们的客户  \n忠于我们的工作  \n在努力工作中充实、完善，并超越自我  \n每天进步一点点  \n今天 \n我就付诸于行动！', metadata={'source': '.\\OneFlower\\易速鲜花员工手册.pdf', 'page': 2}), Document(page_content='易速鲜花集团 \n 3  \n易速鲜花 简介 \n易速鲜花，一个超越一切鲜花运营商的全新概念， 土地犹如一片\n绿色的画布，展示着生机勃勃的花海。我们在这里嫁接了乐、吃、住、\n行、游等元素，打造出一个独特的，富含中国原生态特色的网上鲜花\n服务平台。  \n易速鲜花 ，赋予每一朵鲜花更深的情感内涵。我们的文化展示服\n务包括酒文化、茶文化、农耕文化等，将呈现出多行业业态相互辉映\n及繁荣共存的繁花似锦。', metadata={'source': '.\\OneFlower\\易速鲜花员工手册.pdf', 'page': 3}), Document(page_content='易速鲜花，她以高品位的服务，超前的经营理念，尖端的营 销策\n略和丰富的艺术气质，旨在满足大众的需求，创造独一无二的网上购\n花体验。  \n易速鲜花，她是古老与现代的完美融合，她将带您体验夜郎古国\n的历史风貌，感受穿越时空的神奇。购花不再只是交易，更是一次文\n化之旅、美食之旅、音乐之旅，一场美妙体验的新境界。  \n易速鲜花，她超越了传统网络鲜花运营商单一的经营模式，她将', metadata={'source': '.\\OneFlower\\易速鲜花员工手册.pdf', 'page': 3}), Document(page_content='成为影响并促进中国花卉行业综合经济发展和地位提升的重要力量，\n同时也是 一张崭新的名片。  \n因此，易速鲜花，她不只是售卖鲜花，她记忆的是人类对自身生\n存环境的思考。她带给您的不仅是一束鲜花，更是 一切未来的记忆 带\n给您身心合一的体验，让您在每一次购花过程中都感到心动。  \n易速鲜花，她是这座城市的明灯，她激活了这里的活力，改写了\n这里的历史，推进了这里的发展。我们诚挚地邀请您，一起来到这个', metadata={'source': '.\\OneFlower\\易速鲜花员工手册.pdf', 'page': 3}), Document(page_content='乐土，享受易速鲜花带给您的美好。  \n易速鲜花， 欢迎您的加入。', metadata={'source': '.\\OneFlower\\易速鲜花员工手册.pdf', 'page': 3}), Document(page_content='易速鲜花集团 \n 4  \n目   录 \n第一章  人事管理制度 .............................7  \n       一 员工的招聘与录用 ......................7  \n       二 培训..................................8', metadata={'source': '.\\OneFlower\\易速鲜花员工手册.pdf', 'page': 4}), Document(page_content='三 薪酬与福利 ............................9  \n       四 劳动合同解除与终止 ....................10  \n       五 离职..................................10  \n第二章  员工规范 .................................12', metadata={'source': '.\\OneFlower\\易速鲜花员工手册.pdf', 'page': 4}), Document(page_content='一 行为规范 ..............................12  \n       二 仪容仪表规范 ..........................13  \n       三 个人修养 ..............................18  \n第三章  规范用语 .................................19', metadata={'source': '.\\OneFlower\\易速鲜花员工手册.pdf', 'page': 4}), Document(page_content='五、投资和预算\n\n网站的投资主要用来组建网站的网络公司跟网站项目后期运营的费用，当然也包括项目中期的启动部分，但是绝大部分是为了用于开展业务方面的费用。网站在开发结束到运行开始以及到开始盈利估计总共需要大概200万的投资。前期可以只需小部分资金提供网站的运营，后期在网站推广过后将通过其他方面的融资得到资金以开展业务跟商家进行合作以达到盈利的目的。\n\n六、融资方案（资金筹措及投资方式）', metadata={'source': '.\\OneFlower\\易速鲜花运营指南.docx'}), Document(page_content='项目的融资方案以种子资金为主风险投资为辅。种子资金可以分期投入资金，并且投资者等投资风险将由项目人员全力承担。种子资金投入的资金量可以较小，作为项目的启动资金，项目后期将会继续通过第三方融资来获得资金，种子资金获得的投资回报率也将会比风险投资要少。\n\n风险投资同样也可以分期注入，但是投资风险将与项目小组共同承担，但是投资回报率将会比种子资金加大。融资具体的方案会进行具体洽谈以确定。', metadata={'source': '.\\OneFlower\\易速鲜花运营指南.docx'}), Document(page_content='Rose: Love, Passion, Beauty\nCarnation: Maternal Love, Innocence, Respect\nLily: Purity, Nobility, Blessings\nTulip: Perfect Love, Passion, Tenderness\nDaisy: Innocence, Beauty, Hope', metadata={'source': '.\\OneFlower\\花语大全.txt'}), Document(page_content='Peony: Prosperity, Wealth, Happiness\nSunflower: Loyalty, Sunshine, Positivity\nGypsophila: Purity, Romance, Beautiful Dreams\nPeach Blossom: Romantic Luck, Beautiful Fate, Happiness', metadata={'source': '.\\OneFlower\\花语大全.txt'}), Document(page_content='Hydrangea: Sincerity, Gratitude, Best Wishes\nPhalaenopsis: Noble, Elegant, Beautifully Moving\nCherry Blossom: Beauty, Transience, Wonderful Moments\nLily of the Valley: Happiness, Purity, Deep Love', metadata={'source': '.\\OneFlower\\花语大全.txt'}), Document(page_content='Chrysanthemum: Strength, Longevity, Sincere Friendship\nMarigold: Beauty, Blessings, Wellness\nViolet: Eternal Love, Purity, Chastity\nEdelweiss: Courage, Sincere Love, Preciousness', metadata={'source': '.\\OneFlower\\花语大全.txt'}), Document(page_content='Bellflower: Hope, Everlasting Love, Humility\nForget-Me-Not: Loyalty, True Love, Beautiful Memories\nPaeonia: Fragrance, Wealth, Beautiful Posture\nWisteria: Gentleness, Sentimentality, Protective Love', metadata={'source': '.\\OneFlower\\花语大全.txt'}), Document(page_content='Lavender: Tranquility, Innocence, Pursuit of Love\nFoxglove: Beauty, Joy, Blessings\nDianthus: Delicate Thoughts, Sincerity, Romance\nMagnolia: Nobility, Elegance, Eternal Love', metadata={'source': '.\\OneFlower\\花语大全.txt'}), Document(page_content='Lilac: First Love, Youth, Beautiful Memories\nLotus: Freshness, Purity, Excellence\nGinkgo: Persistence, Friendship, Steadfast Heart\nSnowdrop: Hope, New Beginnings, First Bloom', metadata={'source': '.\\OneFlower\\花语大全.txt'}), Document(page_content='Anthurium: Passion, Attraction, Happy Love', metadata={'source': '.\\OneFlower\\花语大全.txt'})]


第三个参数vectorstore 因为程序已经出错，打印不出来了

**Comment by xing61** [comment]
![xiaoyi客服1号-小](https://github.com/xing61/xiaoyi-robot/assets/38256442/25f92668-6f24-4a5e-a6a8-00d42ad002d1)
加微信一起看看？解决下

**Comment by tjlcast** [comment]
langchain开发能否兼容呢，key和url如何替换呢？

**Comment by xing61** [comment]
> langchain开发能否兼容呢，key和url如何替换呢？

可以的。核心思想是要找到langchain是怎么调用的openai，然后替换掉他调用时的key和url即可。我记得langchain应该是取得环境变量中的值：
![image](https://github.com/xing61/xiaoyi-robot/assets/38256442/3e306380-7b66-4e64-b002-556537317970)

**Comment by higginH** [comment]
我也遇到了这个问题，有解决方案了吗？

**Comment by xing61** [comment]
> 我也遇到了这个问题，有解决方案了吗？

已经fix了。可以参考下：

import os
import requests
import time
import json
import time
from langchain.llms import OpenAI
from langchain.embeddings.openai import OpenAIEmbeddings

API_SECRET_KEY = "你的智增增的key";
BASE_URL = "https://flag.smarttrot.com/v1"; #智增增的base-url

os.environ["OPENAI_API_KEY"] = API_SECRET_KEY
os.environ["OPENAI_API_BASE"] = BASE_URL

# 根据你提供的输入来预测输出，也就是进行问答：
def text():
    llm = OpenAI(temperature=0.9)
    text = "What would be a good company name for a company that makes colorful socks?"
    print(llm(text))

def embedding():
    embeddings = OpenAIEmbeddings()
    #text = "This is a test document."
    #doc_result = embeddings.embed_documents([text]);
    doc_result = embeddings.embed_documents(
        [
            "Hi there!",
            "Oh, hello!",
            "What's your name?",
            "My friends call me World",
            "Hello World!"
        ]
    );
    print(doc_result)
    # 嵌入查询
    embedded_query = embeddings.embed_query("What was the name mentioned in the conversation?")
    print(embedded_query)

if __name__ == '__main__':
    #text();
    embedding();
